version: '3.8'

services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    working_dir: /workspaces/graphql-client-boilerplate